// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEFpnFFZp-zfuAsmzK6y6LCI_2Uk4Ros8',
    appId: '1:299868347035:web:68d58d9cb4cc2baa32843e',
    messagingSenderId: '299868347035',
    projectId: 'english-vocab-app-7ae52',
    authDomain: 'english-vocab-app-7ae52.firebaseapp.com',
    storageBucket: 'english-vocab-app-7ae52.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr4iUWB1OF-ARgGiLozUB6W6h0eIWXzVE',
    appId: '1:299868347035:android:412ae07facb00a4f32843e',
    messagingSenderId: '299868347035',
    projectId: 'english-vocab-app-7ae52',
    storageBucket: 'english-vocab-app-7ae52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDakw3uKl1joYKgpHyKmH1simYWZFeZwBs',
    appId: '1:299868347035:ios:224b85478eda2ea932843e',
    messagingSenderId: '299868347035',
    projectId: 'english-vocab-app-7ae52',
    storageBucket: 'english-vocab-app-7ae52.firebasestorage.app',
    iosBundleId: 'com.example.englishApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDakw3uKl1joYKgpHyKmH1simYWZFeZwBs',
    appId: '1:299868347035:ios:224b85478eda2ea932843e',
    messagingSenderId: '299868347035',
    projectId: 'english-vocab-app-7ae52',
    storageBucket: 'english-vocab-app-7ae52.firebasestorage.app',
    iosBundleId: 'com.example.englishApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEFpnFFZp-zfuAsmzK6y6LCI_2Uk4Ros8',
    appId: '1:299868347035:web:5925fb5c577bd22a32843e',
    messagingSenderId: '299868347035',
    projectId: 'english-vocab-app-7ae52',
    authDomain: 'english-vocab-app-7ae52.firebaseapp.com',
    storageBucket: 'english-vocab-app-7ae52.firebasestorage.app',
  );
}
